[package]
name = "shellymetry"
version = "0.1.0"
authors = ["dmathieu <damien.mathieu@auth0.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
